import { describe, expect, it } from "vitest";
import { classifyTextCommand, registerTextCommand } from "../src/features/01-text-command.js";
import { ToolRegistry } from "../src/agent/tools.js";
import { makeAgentDeps } from "./helpers.js";
import { MockWhatsAppClient } from "../src/whatsapp/mock.js";

describe("classifyTextCommand", () => {
  it("returns intent + body", () => {
    expect(classifyTextCommand("remind me to drink water")).toEqual({
      intent: "set_reminder",
      body: "remind me to drink water",
    });
  });
});

describe("reply_to_user tool", () => {
  it("sends text via WhatsApp client", async () => {
    const r = new ToolRegistry();
    registerTextCommand(r);
    const wa = new MockWhatsAppClient();
    const deps = makeAgentDeps({ whatsapp: wa });
    const tool = r.get("reply_to_user")!;
    await tool.handler(
      { text: "hello back" },
      { userPhone: "+9100", now: new Date(), timezone: "UTC", deps },
    );
    expect(wa.sent[0]).toMatchObject({ to: "+9100", body: "hello back" });
  });

  it("removes manual Claude Code/nwp instructions from model replies", async () => {
    const r = new ToolRegistry();
    registerTextCommand(r);
    const wa = new MockWhatsAppClient();
    const deps = makeAgentDeps({ whatsapp: wa });
    const tool = r.get("reply_to_user")!;

    await tool.handler(
      {
        text: [
          "Feature queue: 95 pending, 1 shipped.",
          "Run *nwp in Claude Code to kick off the next build!",
        ].join("\n"),
      },
      { userPhone: "+9100", now: new Date(), timezone: "UTC", deps },
    );

    expect(wa.sent[0].body).toContain("Feature queue: 95 pending, 1 shipped.");
    expect(wa.sent[0].body).not.toContain("Claude Code");
    expect(wa.sent[0].body).not.toContain("*nwp");
  });

  it("suppresses noisy saved/working receipts generated by the model", async () => {
    const r = new ToolRegistry();
    registerTextCommand(r);
    const wa = new MockWhatsAppClient();
    const deps = makeAgentDeps({ whatsapp: wa });
    const tool = r.get("reply_to_user")!;

    await tool.handler(
      { text: "Saved. Working on it." },
      { userPhone: "+9100", now: new Date(), timezone: "UTC", deps },
    );

    expect(wa.sent).toHaveLength(0);
  });

  it("removes noisy receipt lines but keeps the actual answer", async () => {
    const r = new ToolRegistry();
    registerTextCommand(r);
    const wa = new MockWhatsAppClient();
    const deps = makeAgentDeps({ whatsapp: wa });
    const tool = r.get("reply_to_user")!;

    await tool.handler(
      { text: "Saved. Working on it.\nHey Nitesh! What can I do for you today?" },
      { userPhone: "+9100", now: new Date(), timezone: "UTC", deps },
    );

    expect(wa.sent).toHaveLength(1);
    expect(wa.sent[0].body).toBe("Hey Nitesh! What can I do for you today?");
  });

  it("repairs non-English script replies into English when the profile requires English", async () => {
    const r = new ToolRegistry();
    registerTextCommand(r);
    const wa = new MockWhatsAppClient();
    const deps = makeAgentDeps({
      whatsapp: wa,
      profile: { replyLanguage: "English" },
      llm: {
        async complete() {
          return { text: "The current Chief Minister of Gujarat is Bhupendra Patel." };
        },
        async toolStep() {
          return { stopReason: "end_turn", toolCalls: [], text: "" };
        },
      },
    });
    const tool = r.get("reply_to_user")!;

    await tool.handler(
      { text: "ગુજરાતના હાલના મુખ્યમંત્રી ભૂપેન્દ્રભાઈ પટેલ છે." },
      { userPhone: "+9100", now: new Date(), timezone: "UTC", deps },
    );

    expect(wa.sent).toHaveLength(1);
    expect(wa.sent[0].body).toBe("The current Chief Minister of Gujarat is Bhupendra Patel.");
    expect(wa.sent[0].body).not.toMatch(/[\u0A80-\u0AFF]/);
  });
});
